LibraryWeb/urls.py
from django.conf import settings
from django.conf.urls.static import static
import django.contrib.auth.urls as djangoAuth
import  django.contrib.auth.views as auth



from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url = 'catalog/', permanent = True)), #Redirecting to catalog route
    #Django urls for authentication
    # path('accounts/', include(djangoAuth)),
    path('login/', auth.LoginView.as_view(template_name="auth/login.html"), name='login'),
    path('logout/', auth.LogoutView.as_view(template_name="auth/logout.html"), name='logout'),
    path('reset-password/', auth.PasswordResetView.as_view(template_name="auth/password/password-reset.html"), name="password_reset"),
    path('reset-password-done/', auth.PasswordResetDoneView.as_view(template_name="auth/password/password-reset-done.html"), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth.PasswordResetConfirmView.as_view(template_name = 'auth/password/password_reset_confirm.html'), name="password_reset_confirm"),
    path('password-reset-complete/', auth.PasswordResetCompleteView.as_view(template_name='auth/password/password-reset-complete.html'), name='password_reset_complete'),
    

]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.urls import path
from django.views.generic import RedirectView
from .views import (home, BookView, BookDetail, AuthorListView,
                     AuthorDetailView, LoanedBooksByUserListView,
                     AllBorrowedBooks, RenewBooks, AuthorCreate,
                     AuthorUpdate, AuthorDelete, CreateBook,
                     UpdateBook, DeleteBook)


urlpatterns = [
    path('', home, name="home"),
    path('books/', BookView.as_view(), name='book-list'),
    path('book/<str:pk>/', BookDetail.as_view() ,name="book-detail"),
    path('authors/', AuthorListView.as_view(), name="authors"),
    path('author/<str:pk>/', AuthorDetailView.as_view(), name="author-detail"),
    path('mybooks/', LoanedBooksByUserListView.as_view(), name="loaned-books" ),
    path('books-borrowed-out/', AllBorrowedBooks.as_view(), name="books-borrowed-out"),
    path('book/<uuid:pk>/renew/', RenewBooks, name="renew-books"),
    path('create-author/', AuthorCreate.as_view(), name='create-author'),
    path('update/<pk>/author/', AuthorUpdate.as_view(), name="delete-author"),
    path('delete/<pk>/author/', AuthorDelete.as_view(), name="update-author"),
    path('create-book/', CreateBook.as_view(), name="create-book"),
    path('update/book/<pk>/', UpdateBook.as_view(), name='update-book'),
    path('delete/book/<pk>/', DeleteBook.as_view(), name='delete-book')
    




    
]

catalog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import uuid
from datetime import date

# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    date_of_death = models.DateField('Died', null=True, blank=True)
    # books = models.ManyToManyField('Book' )
    

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.first_name} {self.last_name}' 

class Genre(models.Model):
    name = models.CharField(max_length=100,  help_text = "enter a book genre(e.g. Science, Inspirational etc)")

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    # author = models.ManyToManyField(Author)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, )
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    language = models.ForeignKey(Language,  on_delete=models.SET_NULL, null=True)
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    ISBN = models.CharField('ISBN', max_length=13, unique=True,  help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    # availability_status = models.BooleanField(default=False)
    
    def display_genre(self):
        return ', '.join(g.name for g in self.genre.all()[:3])
    def __str__(self):
        return f'{self.title} | {self.author}'
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    

class BookInstance(models.Model):
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book, on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=150)
    due_back = models.DateField(blank=True, null=True)
    status =models.CharField(max_length=1, choices=LOAN_STATUS, default='m',help_text='Book availability',)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    # borrower = models.ForeignKey(User, on_delete=models.CASCADE)
    class Meta:
        ordering = ['due_back']
        verbose_name = 'Book Instance'

    def __str__(self):
        return f'{self.book.title}'
    
    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        if self.due_back:
            return bool(self.due_back and date.today() > self.due_back)
        
    class Meta:
        # …
        permissions = (("can_mark_returned", "Set book as returned"), ("can_renew", "Can renew Borrwed Book") )

    
    def get_absolute_url(self):
        return reverse('bookinstance-detail', args=[str(self.id)])

templates/author_detail.html
{% extends 'base.html' %}
{% block title %} {{author}}{% endblock title %}

{% block content %}
  <h1>Author: {{author }}</h1>

  <p>{{author.date_of_birth}}  {% if author.date_of_death %} - {{author.date_of_death}}{% endif %}</p>
  
  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    <dl>
        {% for book in author.book_set.all %}
          <dt><a class="text-success" href="{{book.get_absolute_url}}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
          <dd>{{book.summary}}</dd>
        {% endfor %}
        </dl>
        
  </div>
 
{% endblock %}

templates/authors.html
{% extends 'base.html' %}
{% block title %} Authors{% endblock title %}

{% block content%}
<h1>List of Authors</h1>

{% if author_list %}
<ul>
    {% for author in author_list %}
    
    <li><a href="{{author.get_absolute_url}}">{{author.first_name}},  {{author.last_name}}</a></li>

    {% endfor %}

</ul>
{% else %}
    <p>There is no author recorded.</p>
 
{% endif %}
{% endblock content %}

templates/base.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library |{% block title %} {% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
</head>
<body>
    <div class="row">
        <div class="sidebar"> {% include 'partials/sidebar.html' %} </div>
        <div class="main-content"> 
            {% block content%} {% endblock content %}
            {% include 'partials/pagination.html'%}
        </div>

    </div>
    
</body>
</html>

templates/book-detail.html
{% extends 'base.html' %}
{% block title %} {{book.title}}{% endblock title %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{book.author.get_absolute_url}}">{{ book.author }}</a></p>
  <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.ISBN }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr />
      <p 
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
 
{% endblock %}

templates/book-list.html
{% extends 'base.html' %}
{% block title %} Books{% endblock title %}

{% block content%}
<h1>Books in the Local Library</h1>

{% if books %}
<ul>
    {% for book in books %}
    
    <li><a href="{{book.get_absolute_url}}">{{book.title}}</a>  ({{book.author}})</li>

    {% endfor %}

</ul>
{% else %}
    <p>There are no books in the library.</p>
 
{% endif %}
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block title %} Home{% endblock title %}

{% block content%}

<h1>Local Library Home</h1>
<p>You have visted this site <strong>{{number_visits}}</strong> times</p>
<p>Welcome to JPC Library, Just trying to build something cool. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos, atque quia suscipit qui sapiente velit dicta autem corrupti architecto facilis possimus numquam ab enim porro doloribus totam molestias quibusdam id!</p>
<h1>Dynamic Content</h1>
The Library has the following record counts:
<ul>
    <li><b>Books:</b> {{bookCount}}</li>
    <li><b>Copies:</b> {{bookIns.count}} </li>
    <li><b>Copies available:</b> {{avCopies.count}}</li>
    <li><b>Authors:</b>{{authors.count}} </li>
</ul>



<p>
    You have visited this page {{ number_visits }} time{{ number_visits|pluralize }}.
  </p>
{% endblock content %}

templates/lonedbookes-by-user.html
{% extends "base.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if borrowedBooks %}
    <ul>

      {% for bk in borrowedBooks %}
      <li class="{% if bk.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bk.book.pk %}">{{ bk.book.title }}</a> ({{ bk.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}